FROM node:14-alpine AS build
RUN apk add --no-cache make gcc g++ python3
WORKDIR /app
COPY lerna.json ./
COPY package.json package-lock.json ./
COPY packages/core/package*.json ./packages/core/
COPY packages/web/package*.json ./packages/web/
RUN npm ci
RUN npx lerna bootstrap
COPY . .
RUN npm run build
RUN npm prune --production
FROM node:14-alpine AS run
WORKDIR /app
ENV NODE_ENV production
COPY --from=build /app/package*.json ./
COPY --from=build /app/node_modules/ ./node_modules/
COPY --from=build /app/packages/core/package*.json ./packages/core/
COPY --from=build /app/packages/web/package*.json ./packages/web/
COPY --from=build /app/packages/web/.next/ ./packages/web/.next/
COPY --from=build /app/packages/web/node_modules/ ./packages/web/node_modules/
EXPOSE 3000
CMD ["npm", "--prefix", "packages/web", "run", "start"]
